### ISSUE TITLE
Suffocation

### ISSUE THREAD

**Issue by Ashley123477** [Interactive-Modding/JurassicWorldRebornMod#32]
Dinosaurs will virtually walk into blocks, suffocating themselves.

**Comment by Darth-Vitiate** [comment]
This only occurs with creative spawned entities am I correct?

**Comment by Ashley123477** [comment]
As of yet, im still trying to figure out how to spawn them without creative, but if this is an already known issue that happens with creative spawned dinosaurs, this can be closed, The dinosaur i spawned in was infact from creative.

**Comment by Demskillz9955** [comment]
I have confirmation that this happens to survival dinos as well

**Comment by Ashley123477** [comment]
Good to know, glad i could help :)
