### ISSUE TITLE
Dinosaurs teleporting through walls

### ISSUE THREAD

**Issue by Fluffy9911** [Interactive-Modding/JurassicWorldRebornMod#33]
I was walking by my giga enclosure and watched a giga somehow phase through a wall. for now I only know of gigas doing this

**Comment by Darth-Vitiate** [comment]
Was this in survival? Did this occur when the giga  went to sleep or woke up from sleeping?

**Comment by Demskillz9955** [comment]
survival yeah I came back from the desert and saw my giga clipping through a wall then it just walked out. my sinoceratops also did this. I think it may have happened when they grow into a wall but idk.

**Comment by Darth-Vitiate** [comment]
Was the enclosure very small? Can you send a screenshot of what the enclosure looks like?

**Comment by Demskillz9955** [comment]
[
![2020-11-29_10 01 22](https://user-images.githubusercontent.com/63360053/100548467-f7f4de00-3229-11eb-8f4b-15de0f9f9e06.png)
](url) and they also seem to want to only be at the bottom area even if I move them to the top part

**Comment by Darth-Vitiate** [comment]
Hmm okay, are you a member of our discord?

**Comment by Demskillz9955** [comment]
yeah my user name is fluffy#9911
