### ISSUE TITLE
Tamed dinosaurs attack their owner

### ISSUE THREAD

**Issue by QuantumExp** [Interactive-Modding/JurassicWorldRebornMod#35]
It seems that certain tamed dinos (e.g. Velociraptor) attack their owner even though they're suppose to be tamed to said player. When I switched from creative to survival, and changed the raptor's last set command from sit to follow, the raptor immediately attacked me. Fortunately, this does not affect Achillobator or the Jurassic World Raptor Squad, but I do not know how many dinos it affects. I will update this as I discover more info regarding which tamable dinos are affected by this bug.

**Comment by Orcrist55** [comment]
It does not affect the Achillobator it does effect the raptor squad.

**Comment by QuantumExp** [comment]
I am aware that the Achillobator is unaffected. The Indoraptor,
Majungasaurus, and all herbivorous pets don't attack their owner either,
but those that should be capable of fighting with you don't fight either.

**Comment by QuantumExp** [comment]
When I first tested this with the raptor squad, they did not attack me. After further testing, well, you already know what happens.
