### ISSUE TITLE
Action Figures and Fresh Skeletons missing textures

### ISSUE THREAD

**Issue by EricDragonFire** [Interactive-Modding/JurassicWorldRebornMod#43]
As stated in the title, the action figure and fresh skeleton textures are missing. I have the latest version of Reborn and Llibrary. I also do not have JurassiCraft installed. Please help

**Comment by Darth-Vitiate** [comment]
Hello! Are you allocating more than 2G of ram? Can you send screenshots?

**Comment by EricDragonFire** [comment]
I'm not home atm but I am currently allocating 8gb of RAM into the game. Will supply screenshots shortly

**Comment by EricDragonFire** [comment]
![2021-04-15_23 45 15](https://user-images.githubusercontent.com/72771642/114968673-d4cb7380-9e44-11eb-8378-794b32672640.png)

**Comment by EricDragonFire** [comment]
Still need help

**Comment by Darth-Vitiate** [comment]
Hello sorry for the late response, what other mods are you using?

**Comment by EricDragonFire** [comment]
18w43aMod1.12.jar
Actually-Additions-Mod-1.12.2.jar
AgriCraft-2.12.0-1.12.0-a6.jar
alcatrazcore-1.0.4.jar
amidst-forge-1.12.2-0.6.2.jar
Anvil-Enchantments-Mod-1.12.2.jar
Aroma1997Core-1.12.2-2.0.0.0.jar
ASM-Mod-1.12.2.jar
avatarmod-1.6.0-alpha.11.jar
backpack-3.0.2-1.12.2.jar
BadMobs-1.12.2-1.1.40.jar
Baublelicious-1.4.0-4.jar
Baubles-1.12-1.5.2.jar
BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar
BetterFps-1.4.8.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
Bookshelf-1.12.2-2.3.590.jar
buildcraft-all-7.99.24.8.jar
cdm-0.4.1-mc1.12.2.jar
cfm-6.3.0-mc1.12.2.jar
Chameleon-1.12-4.1.3.jar
ChestTransporter-1.12.2-2.8.8.jar
chickens-6.1.0.jar
CMDCam_v1.4.6_mc1.12.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
ColoredLights-1.12.2-v-1.2.1.jar
CraftTweaker2-1.12-4.1.20.562.jar
CreativeCore_v1.10.34_mc1.12.2.jar
CTM-MC1.12.2-1.0.2.31.jar
CustomMobSpawner-3.11.5.jar
CustomNPCs_1.12.2(30Jan19).jar
cxlibrary-1.12.1-1.6.1.jar
Cyclic-1.12.2-1.20.1.jar
DoggyTalents-1.12.2-1.15.1.4-universal.jar
dragonfire-0.5.7.0.jar
DragonMounts2-1.12.2-1.6.3.jar
DrZharks MoCreatures Mod-12.0.5.jar
EnchantingPlus-1.12.2-5.0.179.jar
EnchantmentDescriptions-1.12.2-1.1.15.jar
EqualDragons-1.1.jar
ExpandableInventory-1.12.2-1.3.2.jar
expandedbonemeal-1.11-1.2.1.jar
fencejumper-1.12-1.0.5.jar
FenceOverhaul-1.3.4.jar
forge-1.12.2-14.23.5.2854-installer.jar
forge-1.12.2-14.23.5.2855-installer.jar
Forgelin-1.7.4.jar
fossilsarcheology-8.0.5.jar
FriendlyFire-1.12.2-1.5.8.jar
FullscreenWindowed-1.12-1.6.0.jar
GameStages-1.12.2-2.0.115.jar
globalxp-1.12.2-v1.4.10.jar
gravestone-1.10.3.jar
Harvest-1.12-1.2.7-20.jar
hatchery-1.12.2-2.2.2.jar
HorseTweaks_1.12.2-1.0.5.jar
httymd-1.1.0_MC-1.12.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iceandfire-1.9.0.jar
iChunUtil-1.12.2-7.2.1.jar
ido-1.12.2-1.1.0.jar
incontrol-1.12-3.9.16.jar
infinitefluids-1.11-1.2.0.jar
infinitylib-1.12.0.jar
InventoryTweaks-1.63.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.72.847.jar
ironfurnaces-1.3.5.jar
jei_1.12.2-4.16.1.301.jar
JustAFewFish-1.7_for_1.12.jar
LagGoggles-1.12.2-5.8-132.jar
Levels-2-Mod-1.12.2.jar
llibrary-1.7.20-1.12.2.jar
LLOverlayReloaded-1.1.6-mc1.12.2.jar
longfallboots-1.2.1b.jar
Lucky-Block-Mod-1.12.zip
LucraftCore-1.12.2-2.4.10.jar
Mantle-1.12-1.3.3.55.jar
mcef-1.12.2-0.9.jar
MobController-1.12.2-1.1.jar
MoBends_1.12.2-1.0.0-beta-20.06.20.jar
modlist.txt
morechickens-1.12.2-3.1.0.jar
MoreFurnaces-1.12.2-1.10.6.jar
mowziesmobs-1.5.4.jar
OptiFine_1.12.2_HD_U_F5.jar
outfox-0.1.3-mc1.12.2.jar
Patchouli-1.0-21.jar
Portable-Craft-Bench-Mod-1.12.2.jar
RadixCore-1.12.x-2.2.1-universal.jar
RandomThings-MC1.12.2-4.2.7.4.jar
Recipes+  Mod v1.1.jar
RecipesAndMore-1.12.2-1.0.1.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
refinedstorage-1.6.15.jar
Reforged-0.7.5-1.12+.jar
RoguelikeDungeons-1.12.2-1.8.0.jar
simplegenerators-1.12.2-2.0.20.2.jar
Snad-1.12.1-1.7.09.16a.jar
SolarFluxReborn-1.12.2-12.4.11.jar
StorageDrawers-1.12.2-5.3.7.jar
TConstruct-1.12.2-2.13.0.171.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
TickCentral-3.2.jar
tinkersforging-1.1.4.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
Tiquality-FAT-1.12.2-GAMMA-1.8.1-124.jar
TreeChopper-1.12.2-1.2.4.jar
twilightforest-1.12.2-3.11.1021-universal.jar
Uncrafted-Mod-1.12.2.jar
valkyriecompat-1.12.2-2.0.20.1.jar
valkyrielib-1.12.2-2.0.20.1.jar
Vein-Miner-Mod-1.12.2.jar
WailaStages-1.12.2-2.0.23.jar
Wawla-1.12.2-2.5.273.jar
webdisplays-1.12.2-1.0.jar
Xaeros_Minimap_1.17.5_Forge_1.12.jar
xray-1.12.2.jar
[1.12]bspkrsCore-universal-7.6.0.1.jar
[1.12]TreeCapitator-client-1.43.0.jar
[1.12]UncraftingTable-1.8-beta6.jar

**Comment by EricDragonFire** [comment]
Still in need of assistance

**Comment by freopt** [comment]
Have this problem with latest version
