### ISSUE TITLE
Beelzebufo crashes game

### ISSUE THREAD

**Issue by JaitinPrakash** [Interactive-Modding/JurassicWorldRebornMod#64]
I'm encountering a crash related to pathfinding, but it's only caused by the Beelzebufo entity, and I've had no issues with any other dinos. It appears to have a null pointer exception when checking for its "vehicle" and errors extremely aggressively, freezing the game,

[latest.log.gz](https://github.com/Interactive-Modding/JurassicWorldRebornMod/files/11422281/latest.log.gz)

**Comment by m2d2411** [comment]
same for me just with other dinos
