### ISSUE TITLE
Making JWR Compatible with NBT Editing

### ISSUE THREAD

**Issue by TimbreTern** [Interactive-Modding/JurassicWorldRebornMod#71]
I've noticed that when this mod is used in conjuncture with mods like Custom NPCs and More Player Models, all of the dinosaurs that use growth stages only appear as the infant stage when created as an NPC or used as the player model. Unlike other mods that add custom entities, there is no option in the NPC or MPM entity editor to change the model type to adult. There also isn't an option to change the skin type, despite JWR models having multiple skins. I believe this has to do with the NBT tags, correct? Though I'm not sure why they are not showing up, when other similar mods show up just fine.

I have very little experience in Javascript specifically, but I wouldn't mind trying to fix this myself. Is this something you think is valuable? Do you have any advice for me or insights on this before I make a pull request?

**Comment by TimbreTern** [comment]
Closed, I ended up going the long in-game route and utilizing Custom NPCs script editor and NBT editor to do what I wanted. It doesn't work perfectly but I think this is the best fix rather than trying to figure out why JWR interacts the way it does with other mods since it works perfectly fine independently.

**Comment by gamma-02** [comment]
yeah, it works this way because a lot of different devs made a lot of distinct contributions to the codebase, each with their own way of doing things and not telling each other...

it's SO painful to navigate

**Comment by TimbreTern** [comment]
> yeah, it works this way because a lot of different devs made a lot of distinct contributions to the codebase, each with their own way of doing things and not telling each other...
> 
> it's SO painful to navigate

Haha, yeah. I am very thankful for all the free labor that collaborative dev teams do for open access mods like this, but it does come with THAT as a downside. Minecraft's native mappings themselves are a nightmare too, so sometimes that's just how it is. If someone reads this thread and is messing around with this too, my main remaining issue is that I cannot change the size of the dinosaur models if they are being referenced in any other entity spawner, because it is linked to the aging mechanic and the default is a baby. Setting the NBT tags to age the dinosaur does not work, for some reason, but every other change made to the NBT tags does work, such as colour. Looking inside the mod, I'm quite lost with how the aging works in general, honestly.
