### ISSUE TITLE
dinosaurs invisible to everyone that joins my server

### ISSUE THREAD

**Issue by RyanDavanzo** [Interactive-Modding/JurassicWorldRebornMod#73]
so yeah...my friends cant see the dinos :v
we all have the same mods with the same configs

**Comment by Mercenary4Hire** [comment]
Would you be willing to post a copy of your logs so we can see a complete mod list, I suspect its another mod causing the problem.
Also is the dinosaurs being invisible a consistent thing, or does it seem to happen randomly?
